name: Generate docs/index.html with Pandoc

on:
    push:
        branches:
            - main

jobs:
    gen-docs:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: Install texlive and pandoc
              run: |
                  sudo apt-get update
                  sudo apt-get install -y texlive
                  curl -o pandoc-latest.deb -L "https://github.com/jgm/pandoc/releases/download/3.1.6/pandoc-3.1.6-1-amd64.deb"
                  sudo dpkg -i pandoc-latest.deb
                  rm pandoc-latest.deb

            - name: Run script to generate docs/index.html file from README.md
              run: |
                  mkdir -p docs
                  pandoc README.md --metadata title="Labin Ojha" -s -o docs/index.html

            - name: Track the docs folder
              run: |
                  git add docs

            - name: Check for changes
              id: git-status
              run: |
                  git diff --staged --quiet || echo "::set-output name=changes::true"

            - name: Commit changes
              if: steps.git-status.outputs.changes == 'true'
              run: |
                  git config --global user.name "Labin Ojha"
                  git config --global user.email "leabstrait@gmail.com"
                  git commit -am "Update HTML files" --author="GitHub Actions <actions@github.com>"

            - name: Push changes
              if: steps.git-status.outputs.changes == 'true'
              uses: ad-m/github-push-action@v0.6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
